# Assignment-3 — UCS420 “Cognitive Computing”
## Pandas

**Name:** Mehakdeep Kaur  
**Roll No:** 1024170364  
**Class:** 3Q32

## Q1. Create the given dataset using Pandas DataFrame

In [5]:
import pandas as pd

data = {
    "Tid": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    "Refund": ["Yes", "No", "No", "Yes", "No", "No", "Yes", "No", "No", "No"],
    "Marital Status": ["Single", "Married", "Single", "Married", "Divorced",
                       "Married", "Divorced", "Single", "Married", "Single"],
    "Taxable Income": ["125K", "100K", "70K", "120K", "95K", "60K", "220K", "85K", "75K", "90K"],
    "Cheat": ["No", "No", "No", "No", "Yes", "No", "No", "Yes", "No", "Yes"]
}

df = pd.DataFrame(data)
df

   Tid Refund Marital Status Taxable Income Cheat
0    1    Yes         Single           125K    No
1    2     No        Married           100K    No
2    3     No         Single            70K    No
3    4    Yes        Married           120K    No
4    5     No       Divorced            95K   Yes
5    6     No        Married            60K    No
6    7    Yes       Divorced           220K    No
7    8     No         Single            85K   Yes
8    9     No        Married            75K    No
9   10     No         Single            90K   Yes

## Q2. Locate rows 0, 4, 7 and 8 using DataFrame

In [6]:
selected_rows = df.loc[[0, 4, 7, 8]]
selected_rows

   Tid Refund Marital Status Taxable Income Cheat
0    1    Yes         Single           125K    No
4    5     No       Divorced            95K   Yes
7    8     No         Single            85K   Yes
8    9     No        Married            75K    No

## Q3. Navigate the DataFrame

### Q3.1 Select rows from index 3 to 7

In [7]:
df.loc[3:7]

   Tid Refund Marital Status Taxable Income Cheat
3    4    Yes        Married           120K    No
4    5     No       Divorced            95K   Yes
5    6     No        Married            60K    No
6    7    Yes       Divorced           220K    No
7    8     No         Single            85K   Yes

### Q3.2 Select rows from index 4 to 8 and columns 2 to 4

In [8]:
df.iloc[4:9, 2:5]

  Marital Status Taxable Income Cheat
4       Divorced            95K   Yes
5        Married            60K    No
6       Divorced           220K    No
7         Single            85K   Yes
8        Married            75K    No

### Q3.3 Select all rows with column index 1 to 3 (including index 3)

In [9]:
df.iloc[:, 1:4]

  Refund Marital Status Taxable Income
0    Yes         Single           125K
1     No        Married           100K
2     No         Single            70K
3    Yes        Married           120K
4     No       Divorced            95K
5     No        Married            60K
6    Yes       Divorced           220K
7     No         Single            85K
8     No        Married            75K
9     No         Single            90K

## Q4. Read a CSV file and display its first five rows
The Iris dataset is stored as `Iris.csv` in the same repository so the notebook can be run directly.

In [12]:
import pandas as pd

# Option 1: Check current working directory and list files
import os
print("Current directory:", os.getcwd())
print("Files in directory:", os.listdir())

# Option 2: Use full file path (replace with your actual path)
# iris_df = pd.read_csv("/full/path/to/your/Iris.csv")

# Option 3: Load Iris dataset from seaborn (if available)
import seaborn as sns
iris_df = sns.load_dataset('iris')  # This loads the built-in Iris dataset
iris_df.head()

# Option 4: Load from sklearn (alternative approach)
# from sklearn.datasets import load_iris
# import pandas as pd
# iris_data = load_iris()
# iris_df = pd.DataFrame(iris_data.data, columns=iris_data.feature_names)
# iris_df['target'] = iris_data.target
# iris_df.head()

Current directory: /home/04a455da-c348-4bc6-94d2-1821e6185d2d
Files in directory: ['Untitled1.ipynb', '.pythonstartup.py', 'Untitled.ipynb', '.ipython', '.virtualenvs', '.jupyter', 'assignment 4 of mehakdeep  (1).ipynb', 'Untitled2.ipynb', 'README.ipynb', '.local', '1024170364_faq_data.csv', '.bashrc', '.profile', '.npm', '.vimrc', 'anaconda_projects', '.ipynb_checkpoints', '.anaconda', 'aqssignment 2 of mehakdeep .ipynb', '.gitconfig', '.conda', 'Assignment_3_Mehakdeep_Kaur (1).ipynb']

Matplotlib is building the font cache; this may take a moment.

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

## Q5. Delete row 4 and column 3 from the CSV DataFrame

In [13]:
iris_modified = iris_df.drop(index=4)
iris_modified = iris_modified.drop(columns=iris_modified.columns[3])

iris_modified.head(10)

    sepal_length  sepal_width  petal_length species
0            5.1          3.5           1.4  setosa
1            4.9          3.0           1.4  setosa
2            4.7          3.2           1.3  setosa
3            4.6          3.1           1.5  setosa
5            5.4          3.9           1.7  setosa
6            4.6          3.4           1.4  setosa
7            5.0          3.4           1.5  setosa
8            4.4          2.9           1.4  setosa
9            4.9          3.1           1.5  setosa
10           5.4          3.7           1.5  setosa

## Q6. Create and analyze `employees.csv`

In [14]:
employees_data = {
    "Employee_ID": [101, 102, 103, 104, 105],
    "Name": ["Alice", "Bob", "Charlie", "Diana", "Edward"],
    "Department": ["HR", "IT", "IT", "Marketing", "Sales"],
    "Age": [29, 34, 41, 28, 38],
    "Salary": [50000, 70000, 65000, 55000, 60000],
    "Years_of_Experience": [4, 8, 10, 3, 12],
    "Joining_Date": ["2020-03-15", "2017-07-19", "2013-06-01", "2021-02-10", "2010-11-25"],
    "Gender": ["Female", "Male", "Male", "Female", "Male"],
    "Bonus": [5000, 7000, 6000, 4500, 5000],
    "Rating": [4.5, 4.0, 3.8, 4.7, 3.5]
}

employees = pd.DataFrame(employees_data)
employees.to_csv("employees.csv", index=False)

employees

,Employee_ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating
0,101,Alice,HR,29,50000,4,2020-03-15,Female,5000,4.5
1,102,Bob,IT,34,70000,8,2017-07-19,Male,7000,4.0
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8
3,104,Diana,Marketing,28,55000,3,2021-02-10,Female,4500,4.7
4,105,Edward,Sales,38,60000,12,2010-11-25,Male,5000,3.5

### Q6(a). Shape of the DataFrame

In [15]:
print("Shape:", employees.shape)

Shape: (5, 10)

### Q6(b). Summary of the DataFrame

In [16]:
employees.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Employee_ID          5 non-null      int64
 1   Name                 5 non-null      object
 2   Department           5 non-null      object
 3   Age                  5 non-null      int64
 4   Salary               5 non-null      int64
 5   Years_of_Experience  5 non-null      int64
 6   Joining_Date         5 non-null      object
 7   Gender               5 non-null      object
 8   Bonus                5 non-null      int64
 9   Rating               5 non-null      float64
dtypes: float64(1), int64(5), object(4)
memory usage: 532.0+ bytes

### Q6(c). Descriptive statistics

In [11]:
employees.describe()

       Employee_ID        Age  ...   Bonus    Rating
count     5.000000   5.000000  ...     5.0  5.000000
mean    103.000000  34.000000  ...  5500.0  4.100000
std       1.581139   5.612486  ...  1000.0  0.494975
min     101.000000  28.000000  ...  4500.0  3.500000
25%     102.000000  29.000000  ...  5000.0  3.800000
50%     103.000000  34.000000  ...  5000.0  4.000000
75%     104.000000  38.000000  ...  6000.0  4.500000
max     105.000000  41.000000  ...  7000.0  4.700000

[8 rows x 6 columns]

### Q6(d). First 5 rows and last 3 rows

In [17]:
print("First 5 rows:")
display(employees.head(5))

print("Last 3 rows:")
display(employees.tail(3))

First 5 rows:

,Employee_ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating
0,101,Alice,HR,29,50000,4,2020-03-15,Female,5000,4.5
1,102,Bob,IT,34,70000,8,2017-07-19,Male,7000,4.0
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8
3,104,Diana,Marketing,28,55000,3,2021-02-10,Female,4500,4.7
4,105,Edward,Sales,38,60000,12,2010-11-25,Male,5000,3.5

Last 3 rows:

,Employee_ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8
3,104,Diana,Marketing,28,55000,3,2021-02-10,Female,4500,4.7
4,105,Edward,Sales,38,60000,12,2010-11-25,Male,5000,3.5

### Q6(e). Calculate required statistics

In [18]:
average_salary = employees["Salary"].mean()
total_bonus = employees["Bonus"].sum()
youngest_age = employees["Age"].min()
highest_rating = employees["Rating"].max()

print("Average Salary:", average_salary)
print("Total Bonus:", total_bonus)
print("Youngest Employee's Age:", youngest_age)
print("Highest Performance Rating:", highest_rating)

Average Salary: 60000.0
Total Bonus: 27500
Youngest Employee's Age: 28
Highest Performance Rating: 4.7

### Q6(f). Sort DataFrame by Salary in descending order

In [19]:
sorted_employees = employees.sort_values(by="Salary", ascending=False)
sorted_employees

,Employee_ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating
1,102,Bob,IT,34,70000,8,2017-07-19,Male,7000,4.0
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8
4,105,Edward,Sales,38,60000,12,2010-11-25,Male,5000,3.5
3,104,Diana,Marketing,28,55000,3,2021-02-10,Female,4500,4.7
0,101,Alice,HR,29,50000,4,2020-03-15,Female,5000,4.5

### Q6(g). Categorize employees based on performance rating

In [20]:
def performance_category(rating):
    if rating >= 4.5:
        return "Excellent"
    elif rating >= 4.0:
        return "Good"
    else:
        return "Average"

employees["Performance"] = employees["Rating"].apply(performance_category)
employees

,Employee_ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating,Performance
0,101,Alice,HR,29,50000,4,2020-03-15,Female,5000,4.5,Excellent
1,102,Bob,IT,34,70000,8,2017-07-19,Male,7000,4.0,Good
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8,Average
3,104,Diana,Marketing,28,55000,3,2021-02-10,Female,4500,4.7,Excellent
4,105,Edward,Sales,38,60000,12,2010-11-25,Male,5000,3.5,Average

### Q6(h). Identify missing values

In [16]:
print(employees.isnull().sum())

Employee_ID            0
Name                   0
Department             0
Age                    0
Salary                 0
Years_of_Experience    0
Joining_Date           0
Gender                 0
Bonus                  0
Rating                 0
Performance            0
dtype: int64

### Q6(i). Rename `Employee_ID` to `ID`

In [21]:
employees.rename(columns={"Employee_ID": "ID"}, inplace=True)
employees

,ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating,Performance
0,101,Alice,HR,29,50000,4,2020-03-15,Female,5000,4.5,Excellent
1,102,Bob,IT,34,70000,8,2017-07-19,Male,7000,4.0,Good
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8,Average
3,104,Diana,Marketing,28,55000,3,2021-02-10,Female,4500,4.7,Excellent
4,105,Edward,Sales,38,60000,12,2010-11-25,Male,5000,3.5,Average

### Q6(j)(i). Employees with more than 5 years of experience

In [22]:
more_than_5_years = employees[employees["Years_of_Experience"] > 5]
more_than_5_years

,ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating,Performance
1,102,Bob,IT,34,70000,8,2017-07-19,Male,7000,4.0,Good
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8,Average
4,105,Edward,Sales,38,60000,12,2010-11-25,Male,5000,3.5,Average

### Q6(j)(ii). Employees belonging to the IT department

In [23]:
it_employees = employees[employees["Department"] == "IT"]
it_employees

,ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating,Performance
1,102,Bob,IT,34,70000,8,2017-07-19,Male,7000,4.0,Good
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8,Average

### Q6(k). Add Tax column with 10% deduction from Salary

In [24]:
employees["Tax"] = employees["Salary"] * 0.10
employees

,ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating,Performance,Tax
0,101,Alice,HR,29,50000,4,2020-03-15,Female,5000,4.5,Excellent,5000.0
1,102,Bob,IT,34,70000,8,2017-07-19,Male,7000,4.0,Good,7000.0
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8,Average,6500.0
3,104,Diana,Marketing,28,55000,3,2021-02-10,Female,4500,4.7,Excellent,5500.0
4,105,Edward,Sales,38,60000,12,2010-11-25,Male,5000,3.5,Average,6000.0

### Q6(l). Save the modified DataFrame to a new CSV file

In [25]:
employees.to_csv("employees_modified.csv", index=False)

print("Modified DataFrame saved as employees_modified.csv")

Modified DataFrame saved as employees_modified.csv